<h1 class="font-bold text-3xl">Return & Refund Policy</h1>
<p>Updated at 2024-11-20</p>

<h1 class="font-bold text-2xl mt-5">Definitions and key terms</h1>
<p>To help explain things as clearly as possible in this Return & Refund Policy, every time any of these terms are referenced, are strictly defined as:</p>
 <ul>
   <li>Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
   <li>Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Orion, that is responsible for your information under this Return & Refund Policy.</li>
   <li>Customer: refers to the company, organization or person that signs up to use the Orion Service to manage the relationships with your consumers or service users.</li>
   <li>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Orion and use the services.</li>
   <li>Service: refers to the service provided by Orion as described in the relative terms (if available) and on this platform.</li>
   <li>Website:  site, which can be accessed via this URL: https://www.togetheronorion.com</li>
   <li>You: a person or entity that is registered with Orion to use the Services.</li>
 </ul>
 
<h1 class="font-bold text-2xl mt-5">Return & Refund Policy</h1>
<p>Thanks for shopping at Orion. We appreciate the fact that you like to buy the stuff we provide. We also want to make sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our products.</p>
<p>As with any shopping experience, there are terms and conditions that apply to transactions at Orion. We’ll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Orion, you agree to the terms set forth below along with  Policy.</p>
<p>If there’s something wrong with the  you bought, or if you are not happy with it, you have 2 weeks to issue a refund and return your game.</p>
<h1 class="font-bold text-2xl mt-5">Refunds</h1>
<p>We at ourselves to serving our customers with the best products. Every single product that you choose is thoroughly inspected and checked for defects. We do this to ensure that you fall in love with our products.</p>
<p>Sadly, there are times when we may not have the product(s) that you choose may face some issues with our quality check. In such cases, we may have to cancel your order. You will be intimated about it in advance so that you don't have to worry unnecessarily about your order. You will be refunded once our team confirms your request.</p>
<p>We will revise your returned product as soon as we receive it and if it follows the guidelines addressed above, we will proceed to issue a refund of your purchase. Your refund may take a couple of days to process but you will be notified when you receive your money.</p>
<h1 class="font-bold text-2xl mt-5">Your Consent</h1>
<p>By using our website, registering an account, or making a purchase, you hereby consent to our Return & Refund Policy and agree to its terms.</p>

<h1 class="font-bold text-2xl mt-5">Changes To Our Return & Refund Policy</h1>
<p>Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Return & Refund Policy. If you do not want to agree to this or any updated Return & Refund Policy, you can delete your account.</p>

<h1 class="font-bold text-2xl mt-5">Contact Us</h1>
<p>If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.</p>
<ul><li>Via Email: contact@togetheronorion.com</li><li>Via this Link:  https://www.togetheronorion.com/support/contact</li>